//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NopSolutions.NopCommerce.Web.Administration.Modules {
    
    
    public partial class CategorySEOControl {
        
        /// <summary>
        /// lblCategoryMetaKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.ToolTipLabelControl lblCategoryMetaKeywords;
        
        /// <summary>
        /// txtMetaKeywords control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMetaKeywords;
        
        /// <summary>
        /// lblCategoryMetaDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.ToolTipLabelControl lblCategoryMetaDescription;
        
        /// <summary>
        /// txtMetaDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMetaDescription;
        
        /// <summary>
        /// lblCategoryMetaTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.ToolTipLabelControl lblCategoryMetaTitle;
        
        /// <summary>
        /// txtMetaTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtMetaTitle;
        
        /// <summary>
        /// lblCategorySEName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.ToolTipLabelControl lblCategorySEName;
        
        /// <summary>
        /// txtSEName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSEName;
        
        /// <summary>
        /// lblCategoryPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.ToolTipLabelControl lblCategoryPageSize;
        
        /// <summary>
        /// txtPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.Administration.Modules.NumericTextBox txtPageSize;
    }
}
